// <auto-generated />
namespace PokerBrain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class renameusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201407171010325_rename-user-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
